#!/usr/bin/env bash
set -eo pipefail

./manifest | while read -r line; do
  source=$(realpath "$PWD/$line")
  target=$(realpath -s ~/.local/bin/"$line")
  ln -s -f "$source" "$target"
  echo "installed at ${target/$HOME/\~}"
done