#!/bin/bash
set -eo pipefail

if [[ -z $1 ]] || [[ $1 = "" ]]; then
	cat <<EOF
Usage: sound-volume VOLUME

Sets sound volume for currently running sound card.
Currently used sound card is determined via 'pactl list sinks' -> RUNNING.

Options
  VOLUME  pactl set-sink-volume volume (e.g. +5%, -10%)
EOF
	exit 1
fi

sink_num=$(pactl list sinks | grep RUNNING -B 1 | head -n 1 | cut -d'#' -f2)
pactl set-sink-volume "$sink_num" "$1"
