#!/bin/bash
set -eo pipefail

version="2.7.0"
./_install_github_release \
  "https://github.com/vultr/vultr-cli/releases/download" \
  "v${version}" \
  "vultr-cli_${version}_linux_64-bit.tar.gz" \
  "vultr-cli_v${version}_checksums.txt" \
  "vultr-cli*" \
  "mv vultr-cli /usr/local/bin/vultr-cli"

ln -sf "/usr/local/bin/vultr-cli" "/usr/local/bin/vultr"